version: 2
updates:
  # Maintain dependencies for pom.xml
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Maven pom.xml"
      include: "scope"
  - package-ecosystem: "maven"
    directory: "/spring-boot"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Maven pom.xml"
      include: "scope"
  - package-ecosystem: "maven"
    directory: "/tomcat"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Maven pom.xml"
      include: "scope"